<a href="https://colab.research.google.com/github/yehorkalchenko81/goit-ds-hw-04/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1 = np.arange(1, 11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_2 = np.zeros((3, 3))
arr_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr_3 = np.random.randint(1, 11, (5, 5))
arr_3

array([[10,  4,  3,  6,  2],
       [ 7,  3,  3, 10,  2],
       [ 6,  7, 10,  5,  5],
       [ 6,  1,  8,  7,  5],
       [ 7,  3,  5,  9,  2]])

In [ ]:
arr_4 = np.random.random((4, 4))
arr_4

array([[0.87630284, 0.21956746, 0.42806205, 0.60279806],
       [0.07885759, 0.11292922, 0.57490925, 0.70054263],
       [0.57609362, 0.59761976, 0.2233681 , 0.68799769],
       [0.81981768, 0.59043359, 0.38173616, 0.37889752]])

In [ ]:
arr_5_1 = np.random.randint(1, 11, 5)
arr_5_2 = np.random.randint(1, 11, 5)
print(arr_5_1 + arr_5_2)
print(arr_5_1 - arr_5_2)
print(arr_5_1 * arr_5_2)

[13 12 13  9 10]
[-1  4 -3  3  6]
[42 32 40 18 16]


In [ ]:
arr_6_1 = np.array([1, 3, 5, 7, 9, 11, 13])
arr_6_2 = np.array([2, 4, 6, 8, 10, 12, 14])
np.dot(arr_6_1, arr_6_2)

504

In [ ]:
arr_7_1 = np.random.randint(1, 11, (2, 2))
arr_7_2 = np.random.randint(1, 11, (2, 3))
np.dot(arr_7_1, arr_7_2)

array([[ 95,  21,  73],
       [102,  22,  74]])

In [33]:
arr_8 = np.random.randint(1, 11, (3 ,3))
arr_8_inv = np.linalg.inv(arr_8)
arr_8_inv

array([[-0.06849315,  0.17808219, -0.01369863],
       [ 0.24200913, -0.09589041, -0.01826484],
       [-0.24657534,  0.04109589,  0.15068493]])

In [40]:
arr_9 = np.random.random((4, 4))
arr_9 = arr_9.T
arr_9

array([[0.17657996, 0.33726105, 0.18667407, 0.73428231],
       [0.59665109, 0.23512079, 0.03276525, 0.67650217],
       [0.93092698, 0.51638907, 0.51891716, 0.61927683],
       [0.68914476, 0.50014991, 0.62372221, 0.10255351]])

In [42]:
arr_10_1 = np.random.randint(1, 11, (3, 4))
arr_10_2 = np.random.randint(1, 11, 4)
np.dot(arr_10_1, arr_10_2)

array([120,  48, 152])

In [44]:
arr_11_1 = np.random.randint(1, 11, (2, 3))
arr_11_2 = np.random.randint(1, 11, 3)
np.dot(arr_10_1, arr_10_2)

array([120,  48, 152])

In [46]:
arr_12_1 = np.random.randint(1, 11, (2, 2))
arr_12_2 = np.random.randint(1, 11, (2, 2))
arr_12_1 * arr_12_2

array([[90,  2],
       [56, 35]])

In [48]:
arr_13_1 = np.random.randint(1, 11, (2, 2))
arr_13_2 = np.random.randint(1, 11, (2, 2))
arr_13_1 * arr_13_2

array([[10, 18],
       [10,  8]])

In [57]:
arr_14 = np.random.randint(1, 101, (5, 5))
arr_14.sum()

1270

In [53]:
arr_15_1 = np.random.randint(1, 11, (4, 4))
arr_15_2 = np.random.randint(1, 11, (4, 4))
arr_15_1 - arr_15_2

array([[-2,  1, -7, -1],
       [-6, -6, -2, -1],
       [ 4, -3, -5,  4],
       [ 0, -5, -7,  1]])

In [73]:
arr_16_1 = np.random.random((3 ,3))
np.sum(arr_16_1, axis=1)

array([1.24703141, 0.9681212 , 1.18443486])

In [76]:
arr_17_1 = np.random.randint(1, 11, (3, 4))
arr_17_2 = arr_17_1 ** 2
arr_17_2

array([[ 25,   9,  25, 100],
       [  4,  25,  25,  16],
       [ 36,  64,   9,  16]])

In [78]:
arr_18_1 = np.random.randint(1, 51, 4)
arr_18_2 = arr_18_1 ** 0.5
arr_18_2

array([4.58257569, 5.19615242, 3.87298335, 4.69041576])